### ISSUE TITLE
Some light on gappa examine assign error

### ISSUE THREAD

**Issue by Robaina** [lczech/gappa#18]
Hi!

thanks for developing gappa examine assign, it has come handy in our application!

I've encountered a segmentation fault error and don't have the slightness idea about what may be triggering it. Perhaps anyone facing the same issue?

gappa examine assign runs fine until it reaches the segmentation fault error, meaning that only a fraction of the placed queries is labelled with taxonomy (that is, until it stops). 

The total number of placed queries is about 4000, would that be cause?

Here is the stdout output:

`Found 1 jplace file
Running the assignment
Not all leafs in the reference tree were taxonomically labelled!(1109 / 1164)
Please check tree leaf label and taxon file taxa name congruency!
Segmentation fault`

I believe that the segmentation fault issue is not related to the above warning (not all leaves being taxonomically labelled), am I right?

any help very welcome, thanks!

**Comment by lczech** [comment]
Hi @Robaina,

a segmentation fault is an internal error in the program due to some mistake in coding. Your 4k query sequences are not the problem - we have used gappa for data with millions or queries ;-)

Could you please share your input files as well as the exact command line call for gappa with us that cause the problem? That's the only way to see what's going on there.

Thanks and so long
Lucas

**Comment by Robaina** [comment]
Hi @lczech ,

thanks for your answer and sorry for the late reply. I could isolate the problem. It was due to some references containing numerical IDs (like labels only being numerical), which coincided with numerical IDs of internal nodes in the tree.  Problem solved after relabelling those references with a prefix...

Thanks and best,
Semidán

**Comment by lczech** [comment]
Hi @Robaina,

happy that you found a solution that works for you. But the segfault should not have happened in the first place. Would you mind sharing the files that cause it to happen, and the command line call to produce the problem, with us here, so that we can solve the problem?

Thanks
Lucas

**Comment by lczech** [comment]
Hi @Robaina, any update on this? I'd still like to investigate the error, if you could send me some files for which it occurs!

**Comment by Robaina** [comment]
Hi @lczech, sorry, I totally forgot to reply to this issue.  I'm afraid I lost track of the original files causing the problem. However, I just run gappa with other ones, in which I intentionally used only numbers as sequence labels (what I thought was the reason why I was getting the reported error), and I cannot reproduce it. Gappa still runs fine.

I don't know what might have caused the segmentation fault back them...But I haven't encountered that error again and we have been using gappa regularly.

Thanks. I'll close this issue.

**Comment by lczech** [comment]
Haha okay, I guess we will never know :-) 

If anything like that happens again, just open another issue!

Cheers
Lucas
