### ISSUE TITLE
Taxonomic assignment: columns of the intermediate result

### ISSUE THREAD

**Issue by ewenewen** [lczech/gappa#3]
Hi Lucas and thanks again for this quickly-evolving tool.

I'd like to use the `assign` subcommand, in order to give the label of the branch on which a query is best placed. For this I guessed that I'd have to use the intermediate result file `per_query_assign` that contains the per-query assignments. However I couldn't find what the four columns exactly mean. Could you give me some light?

Thanks!
Cheers,
Ewen

**Comment by pierrebarbera** [comment]
Hi Ewen!

The columns should be identical to the final output:

```LWR     fract   aLWR    afract  taxopath```

Sorry that it's not documented; fixing it right now. I think I will include the header once at the start of that file as well, even though it is not immediately followed by the actual column data.

Pierre

**Comment by ewenewen** [comment]
Perfect, thanks!
Ewen
