### ISSUE TITLE
Error: In proximity(): close exceeds distant

### ISSUE THREAD

**Issue by johnne** [lczech/gappa#30]
gappa version: `0.7.1`

Hi,
I'm getting an error when using `gappa examine assign`. The command ran for about 7 minutes before throwing the error:

```
Error: In proximity(): close exceeds distant

terminate called after throwing an instance of 'std::invalid_argument'
  what():  In proximity(): close exceeds distant
```

I tried on a smaller dataset (this one that failed has 559023 query sequences) and it seemed to work.

Attaching the full log and input files.
[taxonomy.tsv.gz](https://github.com/lczech/gappa/files/14386353/taxonomy.tsv.gz)
[gappa_assign.MAD.log](https://github.com/lczech/gappa/files/14386344/gappa_assign.MAD.log)
[epa_result.jplace.gz](https://github.com/lczech/gappa/files/14386346/epa_result.jplace.gz)

**Comment by johnne** [comment]
This error disappeared after upgrading to version `0.8.4`.

**Comment by lczech** [comment]
Haha good to know, thanks for the feedback, and please excuse that I did not reply earlier! I would have suggested to test with the latest version ;-)
